name: Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dependencies
      run: |
        sudo apt update
        sudo apt install meson libhidapi-dev libdbus-1-dev libudev-dev

    - name: Build
      run: meson setup ${{github.workspace}}/build && ninja -C ${{github.workspace}}/build

    - name: Install
      run: sudo ninja -C ${{github.workspace}}/build install
